### ISSUE TITLE
Plugin does not handle yanked packages

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape-vyper#17]
For context, we yanked Vyper v0.2.13, so this might be an issue here. I am trying to compile an empty file (where no compiler version is specified) so something strange here is happening.

```bash
$ ape compile
INFO: Compiling 'contracts/Auction.vy'
Traceback (most recent call last):
  File "bin/ape", line 8, in <module>
    sys.exit(cli())
  File "site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "site-packages/ape_compile/_cli.py", line 74, in cli
    contract_types = project.load_contracts(use_cache)
  File "site-packages/ape/managers/project.py", line 117, in load_contracts
    contract_types.update(self.compilers.compile(list(needs_compiling)))
  File "site-packages/ape/managers/compilers.py", line 49, in compile
    for contract_type in self.registered_compilers[extension].compile(paths_to_compile):
  File "site-packages/ape_vyper/compiler.py", line 97, in compile
    result = vvm.compile_source(
  File "site-packages/vvm/main.py", line 64, in compile_source
    compiler_data = _compile(
  File "site-packages/vvm/main.py", line 126, in _compile
    vyper_binary = get_executable(vyper_version)
  File "site-packages/vvm/install.py", line 109, in get_executable
    raise VyperNotInstalled(
vvm.exceptions.VyperNotInstalled: vyper 0.2.13 has not been installed. Use vvm.install_vyper('0.2.13') to install.
```

**Comment by fubuloubu** [comment]
Also note that I manually installed the older `vyper` package (v0.2.12) and the plugin did not properly handle using the installed version when a compiler version is not specified in the version pragma

**Comment by fubuloubu** [comment]
Ah, part of the problem is here:
https://github.com/ApeWorX/ape-vyper/blob/7c4dbeef82c26b160c283b9ed1622ca7a8d03dc8/ape_vyper/compiler.py#L95

This should be `max(self.installed_versions)`

**Comment by fubuloubu** [comment]
@sabotagebeats easy fix, just add a test for a file with no version pragma
